name: CI/CD Sistem Informasi Manajemen Artwork

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Laravel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, sqlite, pdo_sqlite

      - name: Install Composer Dependency
        run: composer install --no-progress --prefer-dist

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Vite Laravel
        run: |
          npm install
          npm run build

  test:
    name: Run Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, sqlite, pdo_sqlite

      - name: Install Composer
        run: composer install --no-progress --prefer-dist

      - name: Create Environment
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Laravel Test
        run: |
          APP_ENV=testing DB_CONNECTION=sqlite DB_DATABASE=":memory:" php artisan test

  deploy:
    name: Deploy Hosting
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy Hosting
        run: echo "Deploy Hosting Berhasil"
