name: CI/CD Sistem Informasi Manajemen Artwork

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  laravel:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0

        env:
          MYSQL_DATABASE: project_skripsi
          MYSQL_ROOT_PASSWORD: root

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring,bcmath,mysql

      - name: Install Composer
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install NPM
        run: npm install

      - name: Create Environment
        run: |
          cp .env.example .env || touch .env

          sed -i 's/^APP_ENV=.*/APP_ENV=testing/' .env
          sed -i 's/^APP_DEBUG=.*/APP_DEBUG=true/' .env

          echo "APP_KEY=base64:uQ+3kx5u5V09sH91bifnzjGieWMxdD0IC5TmYX+hQp8=" >> .env

          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=project_skripsi" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

          echo "CACHE_STORE=file" >> .env
          echo "SESSION_DRIVER=file" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env

          echo "MAIL_MAILER=log" >> .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Clear Laravel
        run: |
          php artisan optimize:clear

      - name: Build Vite
        run: npm run build

      - name: Check Vite
        run: test -f public/build/manifest.json

      - name: Migration Database
        run: php artisan migrate:fresh --force

      - name: Create Storage
        run: php artisan storage:link || true

      - name: Run Test
        run: php artisan test

      - name: Build Laravel
        run: php artisan optimize

      - name: Deploy Hosting
        run: echo "Deploy berhasil"
